export const AI_INFERENCE_QUEUE = 'ai-inference-queue';
export const AI_SERVICE_URL = 'AI_SERVICE_URL';
export const AI_QUEUE_ENABLED = 'AI_QUEUE_ENABLED';
export const AI_CONFIDENCE_THRESHOLD = 'AI_CONFIDENCE_THRESHOLD';
export const AI_REQUEST_TIMEOUT_MS = 'AI_REQUEST_TIMEOUT_MS';
export const AI_SERVICE_API_KEY = 'AI_SERVICE_API_KEY';
export const AI_CIRCUIT_BREAKER_ENABLED = 'AI_CIRCUIT_BREAKER_ENABLED';
